"""rename submission_uuid to submission_hash

Revision ID: 478187230c19
Revises: 20240911_01
Create Date: 2025-12-24 09:15:05.722297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478187230c19'
down_revision: Union[str, None] = '20240911_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('submission_hash', sa.String(length=128), nullable=False))
    op.drop_column('survey_responses', 'submission_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('submission_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('survey_responses', 'submission_hash')
    # ### end Alembic commands ###
