"""Change SurveyComment submission_uuid to submission_hash

Revision ID: 59c875c3cdc2
Revises: 478187230c19
Create Date: 2025-12-24 10:11:55.302098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c875c3cdc2'
down_revision: Union[str, None] = '478187230c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_comments', sa.Column('submission_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_survey_comments_submission_hash'), 'survey_comments', ['submission_hash'], unique=False)
    op.drop_column('survey_comments', 'submission_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_comments', sa.Column('submission_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_survey_comments_submission_hash'), table_name='survey_comments')
    op.drop_column('survey_comments', 'submission_hash')
    # ### end Alembic commands ###
