"""add manager fields to employee in array

Revision ID: 5af9e81126fe
Revises: a79397e434fd
Create Date: 2026-01-22 08:02:20.804343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5af9e81126fe'
down_revision: Union[str, None] = 'a79397e434fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_names', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('employees', sa.Column('manager_emails', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.drop_column('employees', 'manager_email')
    op.drop_column('employees', 'manager_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('manager_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('employees', 'manager_emails')
    op.drop_column('employees', 'manager_names')
    # ### end Alembic commands ###
