"""changed the modal structure

Revision ID: 640e1972799f
Revises: 660689623760
Create Date: 2026-01-25 07:26:17.289749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '640e1972799f'
down_revision: Union[str, None] = '660689623760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_submissions', sa.Column('survey_name', sa.String(length=50), nullable=False))
    op.drop_constraint('uq_employee_submission', 'employee_submissions', type_='unique')
    op.create_unique_constraint('uq_employee_submission', 'employee_submissions', ['employee_id', 'submission_hash', 'survey_name'])
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('employees', 'invite_token_hash')
    op.drop_column('employees', 'survey_names')
    op.drop_column('employees', 'manager_emails')
    op.drop_column('employees', 'invited_at')
    op.drop_column('employees', 'manager_names')
    op.drop_column('employees', 'submitted_at')
    op.add_column('survey_assignments', sa.Column('survey_name', sa.String(length=50), nullable=False))
    op.add_column('survey_assignments', sa.Column('invited_at', sa.DateTime(), nullable=True))
    op.drop_constraint('uq_emp_mgr_assignment', 'survey_assignments', type_='unique')
    op.create_unique_constraint('uq_emp_mgr_assignment', 'survey_assignments', ['employee_id', 'manager_email', 'survey_name'])
    op.add_column('survey_responses', sa.Column('survey_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses', 'survey_name')
    op.drop_constraint('uq_emp_mgr_assignment', 'survey_assignments', type_='unique')
    op.create_unique_constraint('uq_emp_mgr_assignment', 'survey_assignments', ['employee_id', 'manager_email'])
    op.drop_column('survey_assignments', 'invited_at')
    op.drop_column('survey_assignments', 'survey_name')
    op.add_column('employees', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('manager_names', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('invited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('manager_emails', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('survey_names', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('invite_token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('employees', 'created_at')
    op.drop_constraint('uq_employee_submission', 'employee_submissions', type_='unique')
    op.create_unique_constraint('uq_employee_submission', 'employee_submissions', ['employee_id', 'submission_hash'])
    op.drop_column('employee_submissions', 'survey_name')
    # ### end Alembic commands ###
