"""added manager email to employeesubmission

Revision ID: 660689623760
Revises: 837120bbc44a
Create Date: 2026-01-25 06:26:47.861533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660689623760'
down_revision: Union[str, None] = '837120bbc44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_submissions', sa.Column('manager_email', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_submissions', 'manager_email')
    # ### end Alembic commands ###
