"""multiple manager check

Revision ID: 837120bbc44a
Revises: 20aad38acc10
Create Date: 2026-01-22 12:33:01.736492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837120bbc44a'
down_revision: Union[str, None] = '20aad38acc10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_emp_mgr_assignment', 'survey_assignments', ['employee_id', 'manager_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_emp_mgr_assignment', 'survey_assignments', type_='unique')
    # ### end Alembic commands ###
