"""add position and survey_names to employees

Revision ID: a48760b75ef9
Revises: de8681951bba
Create Date: 2026-01-15 08:56:34.187682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a48760b75ef9'
down_revision: Union[str, None] = 'de8681951bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position', sa.String(length=255), nullable=False))
    op.add_column('employees', sa.Column('survey_names', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'survey_names')
    op.drop_column('employees', 'position')
    # ### end Alembic commands ###
