"""add manager fields to employee

Revision ID: a79397e434fd
Revises: a48760b75ef9
Create Date: 2026-01-21 09:40:36.497389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79397e434fd'
down_revision: Union[str, None] = 'a48760b75ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_name', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('manager_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'manager_email')
    op.drop_column('employees', 'manager_name')
    # ### end Alembic commands ###
