"""Add department column to employees

Revision ID: de8681951bba
Revises: 74cbf8926745
Create Date: 2026-01-05 08:14:44.236122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de8681951bba'
down_revision: Union[str, None] = '74cbf8926745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_survey_comments_submission_hash', table_name='survey_comments')
    op.drop_table('survey_comments')
    op.add_column('employees', sa.Column('department', sa.String(length=255), nullable=False))
    op.add_column('survey_responses', sa.Column('department', sa.String(length=255), nullable=False))
    op.drop_constraint('survey_responses_dept_head_id_fkey', 'survey_responses', type_='foreignkey')
    op.drop_column('survey_responses', 'dept_head_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('dept_head_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('survey_responses_dept_head_id_fkey', 'survey_responses', 'department_heads', ['dept_head_id'], ['id'], ondelete='CASCADE')
    op.drop_column('survey_responses', 'department')
    op.drop_column('employees', 'department')
    op.create_table('survey_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dept_head_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('submission_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dept_head_id'], ['department_heads.id'], name='survey_comments_dept_head_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='survey_comments_pkey')
    )
    op.create_index('ix_survey_comments_submission_hash', 'survey_comments', ['submission_hash'], unique=False)
    # ### end Alembic commands ###
